### ISSUE TITLE
Route Enhancers lead to 404 error page

### ISSUE THREAD

**Issue by der-phillip** [itx-informationssysteme/jobapplications#31]
After updating to the current version and including the routeEnhancers configuration, only the 404 error page appears for the two views.

Does anyone still have this error?

**Comment by peerlight** [comment]
same issue here

then suddenly it worked ...

where / how did you import default.yaml?

**Comment by der-phillip** [comment]
This is my content. It is a little different from the [original file](Configuration/Routes/Default.yaml), but it works in version 0.9.12. Now, in version 1.0.1 it doesn't.

I have added **limitToPages** and a new line before **routePath**.

```
routeEnhancers:
  JobapplicationsDetailView:
    type: Extbase
    limitToPages:
      - 286
    namespace: tx_jobapplications_detailview
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Posting::show'
        _arguments:
          slug: posting
    defaultController: 'Posting::list'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
  JobapplicationsApplicationForm:
    type: Extbase
    limitToPages:
      - 287
    namespace: tx_jobapplications_applicationform
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Application::new'
        _arguments:
          slug: posting
    defaultController: 'Application::new'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
```
