### ISSUE TITLE
route enhancer for pagination

### ISSUE THREAD

**Issue by pixelbreit** [itx-informationssysteme/jobapplications#49]
I have created a route enhancer for pagination in the list view. 
Maybe someone has a use for it
```
routeEnhancers:
  JobapplicationsListView:
    type: Extbase
    namespace: tx_jobapplications_frontend
    routes:
      -
        routePath: '/seite-{page}'
        _controller: 'Posting::list'
        _arguments:
          page: '@widget_0/currentPage'
        requirements:
          page: \d+
    defaultController: 'Posting::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '25'
```
