### ISSUE TITLE
pagebrowser in listview does not work when routeEnhancer is on

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#64]
every link leads to the same (first page) result

URL correctly changes to /page-... but the postings remain the same

deactivating the routeEnhancer is a workaround 

routeEnhancers JobapplicationsDetailView and JobapplicationsApplicationForm work properly

PHP 7.4
TYPO3 11.5.10
jobapplications 2.0.0

**Comment by the-andyman** [comment]
I have the same problem. 
With version 1.0.x the page browser works with the routeEnhancer.

Is there a solution for version 2.0.0 in sight, or is there no option but to turn the routeEnhancer off?

**Comment by the-andyman** [comment]
Unfortunately, I still have this problem. Is there no solution for this yet?

**Comment by itx-benjamin-jasper** [comment]
I just tried this, it makes sense, that this is broken because v11 doesn't have widgets anymore, but it should be just the `page` Argument. It doesn't work though, somehow even when specified with a default it expects the parameter to be non empty.

Seems like you've come farther than me though, can you share your the routeEnhancer part of your Site Config?

**Comment by the-andyman** [comment]
Here is the part of my Site Config. I had to remove the "JobapplicationsListView" section, because the pagebrowser isn't working anymore. 

...
```
routeEnhancers:
  JobapplicationsListView:
    type: Extbase
    limitToPages:
      - 1
      - 35
    namespace: tx_jobapplications_frontend
    routes:
      -
        routePath: '/seite-{page}'
        _controller: 'Posting::list'
        _arguments:
          page: 'currentPage'
        requirements:
          page: \d+
    defaultController: 'Posting::list'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '25'
  JobapplicationsDetailView:
    type: Extbase
    limitToPages:
      - 37
    namespace: tx_jobapplications_detailview
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Posting::show'
        _arguments:
          slug: posting
    defaultController: 'Posting::list'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
  JobapplicationsApplicationForm:
    type: Extbase
    limitToPages:
      - 39
    namespace: tx_jobapplications_applicationform
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Application::new'
        _arguments:
          slug: posting
    defaultController: 'Application::new'
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug
  JobapplicationsSuccessPage:
    type: Extbase
    limitToPages:
      - 40
    namespace: tx_jobapplications_successpage
    routes:
      -
        routePath: '/{slug}'
        _controller: 'Application::success'
        _arguments:
          slug: posting
    defaultController: 'Application::success'
    defaults:
      page: ''
    aspects:
      slug:
        type: PersistedAliasMapper
        tableName: tx_jobapplications_domain_model_posting
        routeFieldName: slug

```

The page IDs should be adjusted for testing.

**Comment by itx-benjamin-jasper** [comment]
Right, I've got it now:

```
    JobapplicationsListView:
        type: Extbase
        namespace: tx_jobapplications_frontend
        routes:
            -   routePath: '/'
                _controller: 'Posting::list'
            -   routePath: '/seite-{page}'
                _controller: 'Posting::list'
                _arguments:
                    page: 'page'
                requirements:
                    page: \d+
        defaultController: 'Posting::list'
        aspects:
            page:
                type: StaticRangeMapper
                start: '1'
                end: '25'
```

Only one more thing: It really doesnt like generating links when the page number doesn't exist (fair enough). So if you are getting an error make sure to conditionally only render the link ViewHelper in the Pagination Partial when there is a valid link.

I'll have to fix this in the Default Pagination Template as well.
